hw02_unpack_string completed
DogFox/otus_go_home_work pull request #3
Opened 2024-10-11 17:21 UTC by DogFox

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-10-11 17:24 UTC, DogFox commented
и не придумал что тут можно дописать в тесты)

2024-10-12 11:16 UTC, ityulkanov commented
> и не придумал что тут можно дописать в тесты)

можно дописать различные utf symbols посмотреть как ваш код их запроцессит: 
```
{input: "🙃0", expected: ""},
{input: "🙂9", expected: "🙂🙂🙂🙂🙂🙂🙂🙂🙂"},
{input: "aaф0b", expected: "aab"},

{input: "১২৩", expected: "১২৩"},
{input: "১2২৩0", expected: "১১২"},
{input: "੩4", expected: "੩੩੩੩"},
{input: `искус2тво`, expected: "искусство"},
```

2024-10-12 11:19 UTC, ityulkanov approved these changes

2024-10-12 11:19 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +		_, err := strconv.Atoi(first)
Я бы не рекомендовал основывать логику программы на ошибках. Все же они для другого предназначены. 
Проще написать свой isDigit() '0' < x & x < '9' и уже пользоваться им. Заодно избавитесь от ошибок конверсии всяких не арабских цифр

2024-10-14 03:09 UTC, ityulkanov requested changes
Один из моих тестов всё ещё не отрабатывает как надо: 
```
{input: "🙃0", expected: ""},
```
ломается с panic, посмотрите пожалуйста. Где то: 1 не обрабатывается ошибка 2. некорректно работает логика.

2024-10-14 03:09 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +}
```suggestion
func isDigit(str string) bool {
	return '0' <= str && str <= string'9'
}
```
так тоже будет работать

2024-10-15 03:50 UTC, ityulkanov approved these changes

2024-10-15 04:42 UTC, merged